"""fix_column

Revision ID: 16cc596f1f48
Revises: 5227ad4f39d3
Create Date: 2024-12-02 16:20:04.803489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16cc596f1f48"
down_revision: Union[str, None] = "5227ad4f39d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registered_roles",
        "guild_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint(
        "registered_roles_guild_id_fkey", "registered_roles", type_="foreignkey"
    )
    op.create_foreign_key(None, "registered_roles", "guilds", ["guild_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "registered_roles", type_="foreignkey")
    op.create_foreign_key(
        "registered_roles_guild_id_fkey",
        "registered_roles",
        "guilds",
        ["guild_id"],
        ["guild_id"],
    )
    op.alter_column(
        "registered_roles",
        "guild_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
