"""add member management

Revision ID: 947717d39848
Revises: 38d7f9cda15c
Create Date: 2025-03-20 13:53:27.373519

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "947717d39848"
down_revision = "38d7f9cda15c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_application_notify_channels",
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "guild_id", "channel_id"),
    )
    op.create_table(
        "site_applications",
        sa.Column("original_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_applications")
    op.drop_table("site_application_notify_channels")
    # ### end Alembic commands ###
