"""add due_date for apprival

Revision ID: 5fc6c87cf723
Revises: 9dcb9bf51b37
Create Date: 2025-03-24 23:32:19.845305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc6c87cf723'
down_revision = '9dcb9bf51b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_approvals', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_approvals', 'due_date')
    # ### end Alembic commands ###