"""add due_date notify

Revision ID: fa238d6e3a00
Revises: 3509b45b7bc7
Create Date: 2025-03-25 04:15:48.507579

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa238d6e3a00"
down_revision = "3509b45b7bc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "staff_requests",
        sa.Column("is_due_date_notified", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("staff_requests", "is_due_date_notified")
    # ### end Alembic commands ###
