"""add staff_request

Revision ID: 3509b45b7bc7
Revises: 947717d39848
Create Date: 2025-03-25 03:16:38.736484

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3509b45b7bc7"
down_revision = "947717d39848"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff_requests",
        sa.Column("summary_message_guild_id", sa.BigInteger(), nullable=False),
        sa.Column("summary_message_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("summary_message_id", sa.BigInteger(), nullable=False),
        sa.Column("created_by_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("last_remind_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("summary_message_guild_id", "summary_message_id"),
    )
    op.create_table(
        "staff_request_users",
        sa.Column("staff_request_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("dm_message_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DONE",
                "EXPIRED",
                "CANCELED_BY_REQUESTER",
                name="staffrequeststatus",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["staff_request_id"],
            ["staff_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staff_request_users")
    op.drop_table("staff_requests")
    # ### end Alembic commands ###
