"""add privilege management

Revision ID: d8350fce699f
Revises: b936940374de
Create Date: 2025-03-25 20:02:04.063554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8350fce699f'
down_revision = 'b936940374de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('privilege_remove_queue', sa.Column('permission_level', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privilege_remove_queue', 'permission_level')
    # ### end Alembic commands ###