FROM python:3.13.2-slim

WORKDIR /app

RUN apt update && \
    apt upgrade -y && \
    apt install -y build-essential git nano curl \
    tzdata libpq-dev build-essential make && \
    pip install --upgrade pip poetry

# install requirements
COPY ./discord/poetry.lock ./discord/pyproject.toml ./discord/Makefile /app/
RUN poetry config virtualenvs.create false
RUN make poetry:install

# add poetry files for symlinks
COPY ./pyproject.toml ./poetry.lock /
